### PR TITLE
enable far for pywrapfst compatability

### PR DESCRIPTION
**Pull request by oplatek**
- I updated the build script so pywrapfst[1] can be build upon openfst
- Bumped the build number and kept the same version
- I would suggest rerendering the feedstock if I understand the build / CI process correctly.
The latest CI was failing because it tried to use different version (1.7.1 instad of 1.6.1 and did not updated the SHA1). See https://circleci.com/gh/conda-forge/openfst-feedstock

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by 183amir** [comment]
Hi @oplatek thank you for your contribution. The builds are failing. I am not experienced in compiling openfst myself so I cannot help you there. Please let me know if I can help you.

**Comment by oplatek** [comment]
Hi @183amir,

I am bit lost in conda-smithy and all the tooling.

Where does it this come from?
https://circleci.com/gh/conda-forge/openfst-feedstock/14

I do not think it is from the build script for the openfst itself

**Comment by 183amir** [comment]
I don't know about that one but your pipelines are failing here: https://github.com/conda-forge/openfst-feedstock/pull/9/checks?check_run_id=226821072 
If you remove ` --enable-far=yes` from `build.sh`, will the builds pass here? 
Could you please try that?

**Comment by oplatek** [comment]
Hi @183amir, I reverted my changes and increased only the build number.

I assume it will fail also.

**Comment by 183amir** [comment]
@conda-forge-admin, please rerender

**Comment by 183amir** [comment]
It's not meant to work without rerendering.

**Comment by oplatek** [comment]
Hi @183amir, 

I think it is still failing in the conda smithy stages?

Is this the relevant log https://circleci.com/gh/conda-forge/openfst-feedstock/15?

Thank you for your help!

**Comment by 183amir** [comment]
The tests are failing with:
```
/home/conda/feedstock_root/build_artifacts/openfst_1568908229396/test_tmp/run_test.sh: line 27:
g++: command not found
```

**Comment by 183amir** [comment]
No the relevant logs are here: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=73699&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3

Look at the (failed) checks inside this pull request.

**Comment by 183amir** [comment]
You need to add the compilers as test dependencies.

**Comment by oplatek** [comment]
Hi @183amir,

I am bit confused based on this docs 
https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml#L46
I would assume I should add test section here

```
requirements:
  build:
    - automake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  test:
    - {{ compiler('cxx') }}
```
(Note: I just pushed this change)

However, I do not see the test section here
https://github.com/conda-forge/openfst-feedstock/blob/master/recipe/meta.yaml
so I do not understand why the tests are even run eg. why the run_test.sh is run.

**Comment by 183amir** [comment]
You seem to be confused of several things. I suggest that you go through some documentation first and then try to come back here with questions if you still cannot figure things out.

First, you should be able to compile this package locally by running `conda build openfst-feedstock/recipe`. Please find the documentation on this in conda's (and conda build) docs: https://conda.io/en/latest/
(Hint: that's not where you should put the test requirements.)

Then, try going through conda-forge docs: https://conda-forge.org/docs/ to learn about conda-forge.

**Comment by oplatek** [comment]
Thanks!

**Comment by kylebgorman** [comment]
FYI: `--enable-far` is now supported with `openfst ==1.7.5`, and I have a pending PR to add the Python extension indirectly. Can we close this?

**Comment by oplatek** [comment]
Sure. Thanks!

**Pull request closed without merging**
