### PR TITLE
Upgrade to 1.8.1

### PR DESCRIPTION
**Pull request by kylebgorman**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kylebgorman** [comment]
* On Linux the compiler is missing `<charconv>` (a C++17 feature.)
* On MacOS the compiler is missing `std::optional` and `std::byte` (both C++17 features).

**Comment by chrisburr** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
For linux, I think rerendering has updated GCC 7 to GCC 9. `<charconv>` was added in GCC 8 so I expect that to have fixed things.

For macOS there is a `-std=c++14` after `-std=c++17` so you either need to patch the sources or fix the build script to modify `$CXXFLAGS`:

```
libtool: compile:  x86_64-apple-darwin13.4.0-clang++ -std=c++17 -fno-exceptions -Wno-deprecated-declarations -DHAVE_CONFIG_H -I./../include -D_FORTIFY_SOURCE=2 -isystem $PREFIX/include -mmacosx-version-min=10.9 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -stdlib=libc++ -fvisibility-inlines-hidden -std=c++14 -fmessage-length=0 -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/openfst-1.8.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix -MT flags.lo -MD -MP -MF .deps/flags.Tpo -c flags.cc  -fno-common -DPIC -o .libs/flags.o
```

**Comment by kylebgorman** [comment]
Thanks Chris, I can look into the C++14 issue. (I am one of the upstream maintainers.)

**Comment by kylebgorman** [comment]
@chrisburr are there some docs or code I could read to understand where `-std=c++14` comes from on the Mac OS X build? The `configure.ac` here explicitly sets `-std=c++17` and C++14 isn't mentioned anywhere in the repo. So I don't think the patching option will work...I guess I could just write a magical regular expression to filter CXXFLAGS?

**Comment by chrisburr** [comment]
> I guess I could just write a magical regular expression to filter CXXFLAGS?

That's the easiest, for example:

https://github.com/conda-forge/root-feedstock/blob/093cd1cbee2ab8fd7fab62ea5d6bd79b5789c9c8/recipe/build_root-base.sh#L71-L73

**Pull request merged**
